// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: RegService.proto

package RegService

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	RegService_Register_FullMethodName   = "/regservice.RegService/register"
	RegService_Unregister_FullMethodName = "/regservice.RegService/unregister"
	RegService_Discover_FullMethodName   = "/regservice.RegService/discover"
)

// RegServiceClient is the client API for RegService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RegServiceClient interface {
	Register(ctx context.Context, in *UpdateRegistryParameters, opts ...grpc.CallOption) (*empty.Empty, error)
	Unregister(ctx context.Context, in *UpdateRegistryParameters, opts ...grpc.CallOption) (*empty.Empty, error)
	Discover(ctx context.Context, in *wrappers.StringValue, opts ...grpc.CallOption) (*DiscoveredServers, error)
}

type regServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRegServiceClient(cc grpc.ClientConnInterface) RegServiceClient {
	return &regServiceClient{cc}
}

func (c *regServiceClient) Register(ctx context.Context, in *UpdateRegistryParameters, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, RegService_Register_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *regServiceClient) Unregister(ctx context.Context, in *UpdateRegistryParameters, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, RegService_Unregister_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *regServiceClient) Discover(ctx context.Context, in *wrappers.StringValue, opts ...grpc.CallOption) (*DiscoveredServers, error) {
	out := new(DiscoveredServers)
	err := c.cc.Invoke(ctx, RegService_Discover_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegServiceServer is the server API for RegService service.
// All implementations must embed UnimplementedRegServiceServer
// for forward compatibility
type RegServiceServer interface {
	Register(context.Context, *UpdateRegistryParameters) (*empty.Empty, error)
	Unregister(context.Context, *UpdateRegistryParameters) (*empty.Empty, error)
	Discover(context.Context, *wrappers.StringValue) (*DiscoveredServers, error)
	mustEmbedUnimplementedRegServiceServer()
}

// UnimplementedRegServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRegServiceServer struct {
}

func (UnimplementedRegServiceServer) Register(context.Context, *UpdateRegistryParameters) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedRegServiceServer) Unregister(context.Context, *UpdateRegistryParameters) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unregister not implemented")
}
func (UnimplementedRegServiceServer) Discover(context.Context, *wrappers.StringValue) (*DiscoveredServers, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Discover not implemented")
}
func (UnimplementedRegServiceServer) mustEmbedUnimplementedRegServiceServer() {}

// UnsafeRegServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegServiceServer will
// result in compilation errors.
type UnsafeRegServiceServer interface {
	mustEmbedUnimplementedRegServiceServer()
}

func RegisterRegServiceServer(s grpc.ServiceRegistrar, srv RegServiceServer) {
	s.RegisterService(&RegService_ServiceDesc, srv)
}

func _RegService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRegistryParameters)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegServiceServer).Register(ctx, req.(*UpdateRegistryParameters))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegService_Unregister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRegistryParameters)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegServiceServer).Unregister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegService_Unregister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegServiceServer).Unregister(ctx, req.(*UpdateRegistryParameters))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegService_Discover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrappers.StringValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegServiceServer).Discover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegService_Discover_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegServiceServer).Discover(ctx, req.(*wrappers.StringValue))
	}
	return interceptor(ctx, in, info, handler)
}

// RegService_ServiceDesc is the grpc.ServiceDesc for RegService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RegService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "regservice.RegService",
	HandlerType: (*RegServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "register",
			Handler:    _RegService_Register_Handler,
		},
		{
			MethodName: "unregister",
			Handler:    _RegService_Unregister_Handler,
		},
		{
			MethodName: "discover",
			Handler:    _RegService_Discover_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "RegService.proto",
}
